CREATE TABLE chemical (name text, chemical_group text);
insert into chemical (name, chemical_group) values ("Kalciumhydroxid", "Aktivator");
insert into chemical (name, chemical_group) values ("Magnesium axide", "Aktivator");
insert into chemical (name, chemical_group) values ("Stearinsyra", "Aktivator");
insert into chemical (name, chemical_group) values ("Zinc oxide", "Aktivator");
insert into chemical (name, chemical_group) values ("Benzyldimethylstearylammonium chloride", "Antistat");
insert into chemical (name, chemical_group) values ("Glycerol", "Antistat");
insert into chemical (name, chemical_group) values ("Sodium stearylsulfonate", "Antistat");
insert into chemical (name, chemical_group) values ("Trimethyldodecylammonium chloride", "Antistat");
insert into chemical (name, chemical_group) values ("Cobalt stearate", "Bindemedel");
insert into chemical (name, chemical_group) values ("Kiselsyra", "Bindemedel");
insert into chemical (name, chemical_group) values ("Kolofonium", "Bindemedel");
